# Generated by Django 3.2.9 on 2022-02-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211207_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_clothes_size',
            new_name='product_size',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_shoe_size',
        ),
    ]
