# Generated by Django 3.2.9 on 2022-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comment_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
